/* Copyright © 2017 VMware, Inc. All Rights Reserved.
   SPDX-License-Identifier: BSD-2-Clause

   Generated by: https://github.com/swagger-api/swagger-codegen.git */

package policy

// Policy template placeholder
type PolicyTemplatePlaceholder struct {

	// Placeholder id
	PlaceholderId string `json:"placeholder_id"`

	// Placeholder message
	PlaceholderMessage string `json:"placeholder_message"`
}
