/* Copyright © 2017 VMware, Inc. All Rights Reserved.
   SPDX-License-Identifier: BSD-2-Clause

   Generated by: https://github.com/swagger-api/swagger-codegen.git */

package manager

type IcmpTypeNsService struct {

	ResourceType string `json:"resource_type"`

	// ICMP message code
	IcmpCode int64 `json:"icmp_code,omitempty"`

	// ICMP message type
	IcmpType int64 `json:"icmp_type,omitempty"`

	Protocol string `json:"protocol"`
}
