/* Copyright © 2017 VMware, Inc. All Rights Reserved.
   SPDX-License-Identifier: BSD-2-Clause

   Generated by: https://github.com/swagger-api/swagger-codegen.git */

package manager

type L4PortSetNsService struct {

	ResourceType string `json:"resource_type"`

	DestinationPorts []string `json:"destination_ports,omitempty"`

	L4Protocol string `json:"l4_protocol"`

	SourcePorts []string `json:"source_ports,omitempty"`
}
