/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 3.1.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package manager

type SystemInfoMessage struct {
	HypervisorOsType string `json:"hypervisor_os_type,omitempty"`
	// The pnics.
	Pnics []string `json:"pnics,omitempty"`
}
