/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 3.1.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package manager

// Host node
type HostNode struct {
	// The server will populate this field when returing the resource. Ignored on PUT and POST.
	Links []ResourceLink `json:"_links,omitempty"`
	// Schema for this resource
	Schema string `json:"_schema,omitempty"`
	// Link to this resource
	Self *SelfResourceLink `json:"_self,omitempty"`
	// The _revision property describes the current revision of the resource. To prevent clients from overwriting each other's changes, PUT operations must include the current _revision of the resource, which clients should obtain by issuing a GET operation. If the _revision provided in a PUT request is missing or stale, the operation will be rejected.
	Revision int32 `json:"_revision,omitempty"`
	// Timestamp of resource creation
	CreateTime int64 `json:"_create_time,omitempty"`
	// ID of the user who created this resource
	CreateUser string `json:"_create_user,omitempty"`
	// Timestamp of last modification
	LastModifiedTime int64 `json:"_last_modified_time,omitempty"`
	// ID of the user who last modified this resource
	LastModifiedUser string `json:"_last_modified_user,omitempty"`
	// Protection status is one of the following: PROTECTED - the client who retrieved the entity is not allowed             to modify it. NOT_PROTECTED - the client who retrieved the entity is allowed                 to modify it REQUIRE_OVERRIDE - the client who retrieved the entity is a super                    user and can modify it, but only when providing                    the request header X-Allow-Overwrite=true. UNKNOWN - the _protection field could not be determined for this           entity. 
	Protection string `json:"_protection,omitempty"`
	// Indicates system owned resource
	SystemOwned bool `json:"_system_owned,omitempty"`
	// Description of this resource
	Description string `json:"description,omitempty"`
	// Defaults to ID if not set
	DisplayName string `json:"display_name,omitempty"`
	// Unique identifier of this resource
	Id string `json:"id,omitempty"`
	// Fabric node type, for example 'HostNode', 'EdgeNode' or 'PublicCloudGatewayNode'
	ResourceType string `json:"resource_type"`
	// Opaque identifiers meaningful to the API user
	Tags []Tag `json:"tags,omitempty"`
	// Discovered IP Addresses of the fabric node, version 4 or 6
	DiscoveredIpAddresses []string `json:"discovered_ip_addresses,omitempty"`
	// ID of the Node maintained on the Node and used to recognize the Node
	ExternalId string `json:"external_id,omitempty"`
	// Fully qualified domain name of the fabric node
	Fqdn string `json:"fqdn,omitempty"`
	// IP Addresses of the Node, version 4 or 6. This property is mandatory for all nodes except for automatic deployment of edge virtual machine node. For automatic deployment, the ip address from management_port_subnets property will be considered. 
	IpAddresses []string `json:"ip_addresses,omitempty"`
	// Id of discovered node which was converted to create this node
	DiscoveredNodeId string `json:"discovered_node_id,omitempty"`
	// Login credentials for the host. It is mandatory to provide credentials while adding host to MP to create transport node. 
	HostCredential *HostNodeLoginCredential `json:"host_credential,omitempty"`
	// Indicates host node's maintenance mode state. The state is ENTERING when a task to put the host in maintenance-mode is in progress. 
	MaintenanceModeState string `json:"maintenance_mode_state,omitempty"`
	// The id of the vCenter server managing the ESXi type HostNode
	ManagedByServer string `json:"managed_by_server,omitempty"`
	// Hypervisor type, for example ESXi or RHEL KVM
	OsType string `json:"os_type"`
	// Version of the hypervisor operating system
	OsVersion string `json:"os_version,omitempty"`
	// Specify an installation folder to install the NSX kernel modules for Windows Server. By default, it is C:\\Program Files\\VMware\\NSX\\.
	WindowsInstallLocation string `json:"windows_install_location,omitempty"`
}
