/* Copyright © 2017 VMware, Inc. All Rights Reserved.
   SPDX-License-Identifier: BSD-2-Clause

   Generated by: https://github.com/swagger-api/swagger-codegen.git */

package manager

// A shaper configuration entry that specifies type and metrics
type QosBaseRateShaper struct {
	Enabled bool `json:"enabled"`

	ResourceType string `json:"resource_type,omitempty"`

        // Average bandwidth in Mb/s
        AverageBandwidthMbps int32 `json:"average_bandwidth_mbps,omitempty"`

        // Burst size in bytes
        BurstSizeBytes int32 `json:"burst_size_bytes,omitempty"`

        // Average bandwidth in Mb/s
        PeakBandwidthMbps int32 `json:"peak_bandwidth_mbps,omitempty"`
}
