/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 3.1.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package antreanode

type AntreaNodeRegistrationMessage struct {
	AntreaNode    *AntreaNode        `json:"antrea_node"`
	MsgClientInfo *MsgClientInfo     `json:"msg_client_info"`
	SystemInfo    *SystemInfoMessage `json:"system_info"`
}
